display_name: LunarisEye
package_name: lunariseye
maintainer:
  name: Dark Lunaris
  email: info@DarkLunaris.com
installed_size: 24400
icon: assets/sp.png

# Icon files to install (source path relative to project)
icons:
  - source: assets/sp.png
    name: lunariseye_app
    sizes: [128, 256]

# Desktop entry configuration to auto-generate a .desktop file
desktop:
  exec: /usr/share/lunariseye_app/lunariseye_app %U
  name: LunarisEye
  generic_name: LunarisEye
  icon: lunariseye_app
  categories: Utility;
  terminal: false
  startup_notify: true

categories:
  - Utility
generic_name: LunarisEye
priority: optional
section: x11

